"""Agents responsible for creating, evaluating, and refining prompt designs.

The three agents are intentionally stateless beyond their injected collaborators:
all meaningful state travels as arguments and return values.  This makes each
agent independently testable and composable.

DesignAgent
-----------
Turns an AgentSpec into a PromptDesign.  When an LLMClient is provided, the
heuristic scaffold produced by the tier patterns is enriched with substantive
content generated by the model.  Without a client the system falls back to
heuristic-only output — no degradation of the interface.

EvaluatorAgent
--------------
Runs lightweight, rule-based checks against evaluation scenarios.  No LLM
required for the current implementation.

RefinementAgent
---------------
Suggests edits to a design based on an EvaluationReport.  Currently heuristic;
an LLM could be wired in later via the same LLMClient Protocol.
"""

from __future__ import annotations

import json
import logging
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from typing import Protocol

from .models import (
    AgentSpec,
    AuditFinding,
    EvaluationOutcome,
    EvaluationReport,
    EvaluationResult,
    EvaluationScenario,
    ExecutionPlanBlock,
    ExecutionStep,
    LinguisticAuditReport,
    PromptDesign,
    PromptTier,
    TaskBlock,
)
from .patterns import PatternSelector
from .prompt_templates import (
    AUDIT_TEMPLATE_NAME,
    DESIGN_ENRICHMENT_TEMPLATE_NAME,
    REFINEMENT_TEMPLATE_NAME,
    get_default_template,
    load_template,
)
from .rule_blocks import RuleBlockRegistry

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# LLMClient Protocol
# ---------------------------------------------------------------------------


class LLMClient(Protocol):
    """Minimal interface for LLM providers used by this package.

    Any object with a matching ``generate`` signature satisfies this protocol.
    The ``model`` keyword argument is optional; providers may ignore it if they
    use a fixed model configured at construction time.
    """

    def generate(
        self, prompt: str, *, model: str | None = None
    ) -> str:  # pragma: no cover - interface only
        ...


# ---------------------------------------------------------------------------
# Prompt composition helpers (pure functions — no side effects)
# ---------------------------------------------------------------------------


def _print_verbose_prompt(verbose: bool, title: str, prompt: str) -> None:
    """Print prompt to stdout when verbose is True."""
    if not verbose:
        return
    print("\n" + "=" * 60)
    print(title)
    print("=" * 60)
    print(prompt)
    print("=" * 60 + "\n")


def _format_bullet_section(items: list[str], prefix: str = "  - ") -> str:
    """Format a list as bullet lines; return placeholder when empty."""
    return "\n".join(f"{prefix}{item}" for item in items) if items else "  (none)"


def _get_template(template_loader: Callable[[str], str] | None, name: str) -> str:
    """Return template content from loader or built-in default."""
    if template_loader is not None:
        return template_loader(name)
    return get_default_template(name)


def _build_llm_prompt(
    agent_spec: AgentSpec,
    tier: PromptTier,
    rule_block_names: list[str],
    template_loader: Callable[[str], str] | None = None,
) -> str:
    """Compose the prompt sent to the LLM for task enrichment.

    The prompt follows the orthogonal framework: it is explicit about WHAT it
    wants (Task section) versus HOW (step instructions) and references rule
    blocks by name only.  The LLM is asked to return structured JSON so the
    response can be parsed without fragile string splitting.

    Args:
        agent_spec: The agent specification being designed.
        tier: The selected prompt tier (affects whether execution steps are
            requested).
        rule_block_names: Names of the rule blocks attached to this design.
        template_loader: Optional loader for external template; uses built-in if None.

    Returns:
        A self-contained prompt string ready to be sent to an LLM.
    """
    template = _get_template(template_loader, DESIGN_ENRICHMENT_TEMPLATE_NAME)
    wants_steps = tier in (PromptTier.TIER_2, PromptTier.TIER_3)
    steps_instruction = (
        '\n- "execution_steps": list of 4-6 concise, agent-facing action strings '
        "that operationalise the task for this specific agent (not generic advice)."
        if wants_steps
        else ""
    )
    return template.format(
        role_description=agent_spec.role_description,
        summary=agent_spec.summary,
        tier_value=tier.value,
        inputs_section=_format_bullet_section(agent_spec.primary_inputs),
        outputs_section=_format_bullet_section(agent_spec.primary_outputs),
        constraints_section=_format_bullet_section(agent_spec.constraints),
        rule_block_section=_format_bullet_section(rule_block_names),
        steps_instruction=steps_instruction,
    ).strip()


def _build_refinement_llm_prompt(
    design: PromptDesign,
    feedback: str,
    template_loader: Callable[[str], str] | None = None,
) -> str:
    """Compose the prompt sent to the LLM for a feedback-driven refinement.

    The prompt presents the current design state and the user's feedback, then
    asks the LLM to produce a revised JSON object in the exact same schema as
    the original task enrichment response.  Keeping the schema identical means
    ``_parse_llm_task_enrichment`` can parse the response without any changes.

    Args:
        design: The current PromptDesign to refine.
        feedback: The user's plain-text feedback about what to change.
        template_loader: Optional loader for external template; uses built-in if None.

    Returns:
        A self-contained prompt string ready to be sent to an LLM.
    """
    template = _get_template(template_loader, REFINEMENT_TEMPLATE_NAME)
    wants_steps = design.tier in (PromptTier.TIER_2, PromptTier.TIER_3)
    steps_instruction = (
        '\n- "execution_steps": list of 4-6 concise, agent-facing action strings '
        "that operationalise the revised task."
        if wants_steps
        else ""
    )
    criteria_lines = _format_bullet_section(design.task.acceptance_criteria)
    constraint_lines = _format_bullet_section(design.task.constraints)
    steps_section = ""
    if wants_steps and design.execution_plan is not None:
        step_lines = "\n".join(
            f"  {s.order}. {s.description}"
            for s in sorted(design.execution_plan.steps, key=lambda s: s.order)
        )
        steps_section = f"\nExecution Steps:\n{step_lines}"
    return template.format(
        goal=design.task.goal,
        criteria_lines=criteria_lines,
        constraint_lines=constraint_lines,
        steps_section=steps_section,
        feedback=feedback,
        steps_instruction=steps_instruction,
    ).strip()


def _strip_markdown_fence(raw: str) -> str:
    """Remove optional markdown code fence from LLM response."""
    text = raw.strip()
    if not text.startswith("```"):
        return text
    lines = text.splitlines()
    inner = [line for line in lines[1:] if not line.strip().startswith("```")]
    return "\n".join(inner).strip()


def _parse_task_from_dict(
    data: dict,
    fallback_task: TaskBlock,
    wants_steps: bool,
) -> tuple[TaskBlock, list[ExecutionStep]]:
    """Build TaskBlock and steps from parsed JSON dict; fall back on invalid data."""
    goal = data.get("goal")
    acceptance_criteria = data.get("acceptance_criteria")
    constraints = data.get("constraints")
    if not isinstance(goal, str) or not goal.strip():
        logger.warning("LLM response missing valid 'goal'; using heuristic task.")
        return fallback_task, []

    enriched_task = TaskBlock(
        name=fallback_task.name,
        goal=goal.strip(),
        acceptance_criteria=(
            [str(c) for c in acceptance_criteria]
            if isinstance(acceptance_criteria, list)
            else fallback_task.acceptance_criteria
        ),
        constraints=(
            [str(c) for c in constraints]
            if isinstance(constraints, list)
            else fallback_task.constraints
        ),
        output_format_description=fallback_task.output_format_description,
    )
    steps: list[ExecutionStep] = []
    if wants_steps:
        raw_steps = data.get("execution_steps")
        if isinstance(raw_steps, list):
            steps = [
                ExecutionStep(order=idx + 1, description=str(s).strip())
                for idx, s in enumerate(raw_steps)
                if str(s).strip()
            ]
    return enriched_task, steps


def _parse_llm_task_enrichment(
    raw: str,
    fallback_task: TaskBlock,
    wants_steps: bool,
) -> tuple[TaskBlock, list[ExecutionStep]]:
    """Parse the LLM's JSON response and return an enriched TaskBlock.

    Parsing is defensive: any structural mismatch or missing key causes a
    graceful fallback to the original heuristic values so the caller always
    receives a valid TaskBlock regardless of LLM behaviour.

    Args:
        raw: Raw string returned by the LLM.
        fallback_task: The heuristic TaskBlock to fall back to on parse error.
        wants_steps: Whether to extract ``execution_steps`` from the response.

    Returns:
        A tuple of (enriched TaskBlock, list of ExecutionStep).  The step list
        is empty when ``wants_steps`` is False or when the LLM omitted the key.
    """
    text = _strip_markdown_fence(raw)
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        logger.warning("LLM response was not valid JSON; using heuristic task. Error: %s", exc)
        return fallback_task, []

    if not isinstance(data, dict):
        logger.warning("LLM response parsed but was not a JSON object; using heuristic task.")
        return fallback_task, []

    return _parse_task_from_dict(data, fallback_task, wants_steps)


# ---------------------------------------------------------------------------
# DesignAgent
# ---------------------------------------------------------------------------


@dataclass
class DesignAgent:
    """Agent responsible for turning an AgentSpec into a PromptDesign.

    When ``llm_client`` is provided, ``create_design`` first builds a
    heuristic scaffold via the tier pattern, then calls the LLM to enrich the
    TaskBlock (goal, acceptance criteria, constraints) and — for Tier 2+ —
    replaces the generic execution steps with agent-specific ones.

    Without an LLM client the heuristic scaffold is returned unchanged.  The
    interface is identical in both modes; callers cannot tell the difference.

    The agent is stateless: no design state is kept on the instance.
    """

    pattern_selector: PatternSelector
    rule_block_registry: RuleBlockRegistry
    llm_client: LLMClient | None = None
    verbose: bool = False
    template_loader: Callable[[str], str] | None = None

    def create_design(
        self,
        agent_spec: AgentSpec,
        explicit_tier: str | None = None,
    ) -> PromptDesign:
        """Build a PromptDesign from *agent_spec*, optionally enriched by an LLM.

        Args:
            agent_spec: The agent specification to design for.
            explicit_tier: If given, bypasses auto-tier selection.

        Returns:
            A PromptDesign — heuristic-only when no LLM client is configured,
            LLM-enriched otherwise.
        """
        if explicit_tier is not None:
            tier = PromptTier(explicit_tier)
        else:
            tier = self.pattern_selector.choose_tier(agent_spec)

        pattern = self.pattern_selector.get_pattern(tier)
        design = pattern.build(agent_spec, self.rule_block_registry)

        if self.llm_client is None:
            return design

        return self._enrich_with_llm(design, tier)

    def _merge_enriched_into_design(
        self,
        design: PromptDesign,
        enriched_task: TaskBlock,
        suggested_steps: list[ExecutionStep],
        wants_steps: bool,
    ) -> PromptDesign:
        """Build a new PromptDesign with enriched task and optional new steps."""
        execution_plan = design.execution_plan
        if wants_steps and suggested_steps and execution_plan is not None:
            execution_plan = ExecutionPlanBlock(
                name=execution_plan.name,
                steps=suggested_steps,
            )
        return PromptDesign(
            agent_spec=design.agent_spec,
            tier=design.tier,
            task=enriched_task,
            execution_plan=execution_plan,
            rule_blocks=design.rule_blocks,
        )

    def _enrich_with_llm(self, design: PromptDesign, tier: PromptTier) -> PromptDesign:
        """Send the scaffold to the LLM and merge the enriched fields back.

        This method is intentionally separate from ``create_design`` so it can
        be tested in isolation and so the control flow in ``create_design``
        stays readable.

        Args:
            design: The heuristic scaffold to enrich.
            tier: The tier that was selected for this design.

        Returns:
            A new PromptDesign with the LLM-enriched TaskBlock (and, for Tier
            2+, LLM-suggested execution steps).  If the LLM call or parse
            fails, the original *design* is returned unmodified.
        """
        rule_block_names = [ref.name for ref in design.rule_blocks]
        wants_steps = tier in (PromptTier.TIER_2, PromptTier.TIER_3)
        prompt = _build_llm_prompt(
            design.agent_spec, tier, rule_block_names, self.template_loader
        )
        _print_verbose_prompt(self.verbose, "PROMPT SENT TO LLM", prompt)

        client = self.llm_client
        assert client is not None
        try:
            raw_response = client.generate(prompt)
        except RuntimeError as exc:
            logger.warning("LLM call failed; returning heuristic design. Reason: %s", exc)
            return design

        enriched_task, suggested_steps = _parse_llm_task_enrichment(
            raw_response,
            fallback_task=design.task,
            wants_steps=wants_steps,
        )
        return self._merge_enriched_into_design(
            design, enriched_task, suggested_steps, wants_steps
        )

    def refine_design(self, design: PromptDesign, feedback: str) -> PromptDesign:
        """Revise *design* using the LLM guided by *feedback*.

        The method builds a compact refinement prompt that shows the current
        design state alongside the feedback, then delegates parsing to the same
        ``_parse_llm_task_enrichment`` helper used by ``_enrich_with_llm``.
        This keeps the parsing logic in one place and ensures the refined
        design always has the same structure as any other PromptDesign.

        If no LLM client is configured, or if the LLM call or parse fails, the
        original design is returned unmodified so the caller always gets a
        valid result.

        Args:
            design: The current PromptDesign to revise.
            feedback: The user's plain-text feedback describing the change.

        Returns:
            A new PromptDesign with fields updated according to the feedback,
            or the original *design* when LLM enrichment cannot be performed.
        """
        if self.llm_client is None:
            logger.warning("No LLM client configured; returning original design unchanged.")
            return design

        wants_steps = design.tier in (PromptTier.TIER_2, PromptTier.TIER_3)
        prompt = _build_refinement_llm_prompt(design, feedback, self.template_loader)
        _print_verbose_prompt(self.verbose, "REFINEMENT PROMPT SENT TO LLM", prompt)

        client = self.llm_client
        assert client is not None
        try:
            raw_response = client.generate(prompt)
        except RuntimeError as exc:
            logger.warning("LLM refinement call failed; returning original design. Reason: %s", exc)
            return design

        enriched_task, suggested_steps = _parse_llm_task_enrichment(
            raw_response,
            fallback_task=design.task,
            wants_steps=wants_steps,
        )
        return self._merge_enriched_into_design(
            design, enriched_task, suggested_steps, wants_steps
        )


# ---------------------------------------------------------------------------
# EvaluatorAgent
# ---------------------------------------------------------------------------


@dataclass
class EvaluatorAgent:
    """Agent that evaluates a PromptDesign against scenarios and rule blocks.

    This implementation performs lightweight, rule-based checks without
    invoking an LLM. It focuses on structural alignment between scenarios
    and the Task / constraints in the PromptDesign.
    """

    llm_client: LLMClient | None
    rule_block_registry: RuleBlockRegistry

    def evaluate(
        self,
        design: PromptDesign,
        scenarios: Sequence[EvaluationScenario],
    ) -> EvaluationReport:
        results: list[EvaluationResult] = []

        for scenario in scenarios:
            outcome, notes = self._evaluate_single(design, scenario)
            results.append(
                EvaluationResult(
                    scenario_id=scenario.identifier,
                    outcome=outcome,
                    notes=notes,
                ),
            )

        return EvaluationReport(
            design_identifier=design.agent_spec.identifier,
            results=results,
        )

    def _evaluate_single(
        self,
        design: PromptDesign,
        scenario: EvaluationScenario,
    ) -> tuple[EvaluationOutcome, str]:
        searchable_text = " ".join(
            [
                design.task.goal,
                " ".join(design.task.acceptance_criteria),
                " ".join(design.task.constraints),
            ],
        ).lower()

        missing: list[str] = []
        for expected in scenario.expected_properties:
            if expected.lower() not in searchable_text:
                missing.append(expected)

        if not scenario.expected_properties:
            return EvaluationOutcome.SKIPPED, "No expected properties defined for scenario."

        if missing:
            notes = f"Missing expected properties in design: {', '.join(missing)}"
            return EvaluationOutcome.FAIL, notes

        return EvaluationOutcome.PASS, "All expected properties appear in task or constraints."


# ---------------------------------------------------------------------------
# RefinementAgent
# ---------------------------------------------------------------------------


@dataclass
class RefinementAgent:
    """Agent that suggests refinements to a PromptDesign based on evaluation.

    For now, this agent does not mutate designs. It reports which scenarios
    failed and leaves actual editing decisions to a human or higher-level
    tooling. This keeps PromptDesign as a stable, explicit artefact.
    """

    def propose_refinements(
        self,
        design: PromptDesign,
        report: EvaluationReport,
    ) -> str:
        failed = [result for result in report.results if result.outcome == EvaluationOutcome.FAIL]

        if not failed:
            return "No structural refinements suggested. All scenarios passed."

        lines: list[str] = [
            "Suggested refinements:",
            "",
        ]

        for result in failed:
            lines.append(f"- Scenario '{result.scenario_id}' failed: {result.notes}")

        lines.append("")
        lines.append(
            "Consider updating the Task acceptance criteria or constraints to explicitly cover the missing properties.",
        )

        return "\n".join(lines)


# ---------------------------------------------------------------------------
# LinguisticAuditorAgent
# ---------------------------------------------------------------------------


def _build_audit_llm_prompt(
    design: PromptDesign,
    template_loader: Callable[[str], str] | None = None,
) -> str:
    """Compose the prompt sent to the LLM for a linguistic audit."""
    template = _get_template(template_loader, AUDIT_TEMPLATE_NAME)
    criteria_lines = _format_bullet_section(design.task.acceptance_criteria)
    constraint_lines = _format_bullet_section(design.task.constraints)
    steps_section = ""
    if design.execution_plan is not None:
        step_lines = "\n".join(
            f"  {s.order}. {s.description}"
            for s in sorted(design.execution_plan.steps, key=lambda s: s.order)
        )
        steps_section = f"\nExecution Plan (HOW):\n{step_lines}"
    rule_blocks_section = _format_bullet_section([ref.name for ref in design.rule_blocks])
    return template.format(
        goal=design.task.goal,
        criteria_lines=criteria_lines,
        constraint_lines=constraint_lines,
        steps_section=steps_section,
        rule_blocks_section=rule_blocks_section,
    ).strip()


def _parse_audit_findings(data: dict) -> list[AuditFinding]:
    """Extract list of AuditFinding from parsed JSON."""
    return [
        AuditFinding(
            category=f.get("category", "unknown"),
            location=f.get("location", "unknown"),
            evidence=f.get("evidence", ""),
            suggestion=f.get("suggestion", ""),
        )
        for f in data.get("findings", [])
    ]


def _parse_llm_audit_report(raw: str, design_id: str) -> LinguisticAuditReport:
    """Parse the LLM's JSON response into a LinguisticAuditReport."""
    text = _strip_markdown_fence(raw)
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        logger.warning("LLM audit failed to return valid JSON. Error: %s", exc)
        return LinguisticAuditReport(
            design_identifier=design_id,
            density_score=1,
            orthogonality_score=1,
            summary="Audit failed: LLM response was not valid JSON.",
        )

    findings = _parse_audit_findings(data)
    return LinguisticAuditReport(
        design_identifier=design_id,
        density_score=data.get("density_score", 1),
        orthogonality_score=data.get("orthogonality_score", 1),
        findings=findings,
        summary=data.get("summary", "No summary provided."),
    )


@dataclass
class LinguisticAuditorAgent:
    """Agent that audits a PromptDesign for linguistic and structural debt.

    Like DesignAgent, this agent is stateless and relies on the LLM for its
    analysis of "semantic noise" and "orthogonality violations."
    """

    llm_client: LLMClient
    verbose: bool = False
    template_loader: Callable[[str], str] | None = None

    def audit_design(self, design: PromptDesign) -> LinguisticAuditReport:
        """Analyze *design* for linguistic technical debt and orthogonality leaks.

        Args:
            design: The PromptDesign to audit.

        Returns:
            A LinguisticAuditReport containing findings and scores.
        """
        prompt = _build_audit_llm_prompt(design, self.template_loader)
        _print_verbose_prompt(self.verbose, "AUDIT PROMPT SENT TO LLM", prompt)

        try:
            raw_response = self.llm_client.generate(prompt)
        except RuntimeError as exc:
            logger.warning("LLM audit call failed. Reason: %s", exc)
            return LinguisticAuditReport(
                design_identifier=design.agent_spec.identifier,
                density_score=1,
                orthogonality_score=1,
                summary=f"Audit failed: {exc}",
            )
        return _parse_llm_audit_report(raw_response, design.agent_spec.identifier)
